import textConstants from "./textConstants"
const skills = [
    "Object-Oriented Programming (OOP)",
    "Programming Languages",
    "Design Patterns",
    "Data Structures and Algorithms",
    "Version Control Systems",
    "Database Management",
    "Testing and Debugging",
    "Web Development Skills",
    "Agile Methodologies",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Array Manipulation",
    "Memory Management",
    "Algorithmic Thinking",
    "Error Handling",
    "Multi-dimensional Arrays",
    "Dynamic Arrays",
    "Parallel Processing",
    "Vectorization",
    "Functional Programming with Arrays",
    "Optimizing Array Access"
  ]

  const formDataConfig = {
    fullName: {
        id: 'fullname',
        inputType: textConstants.INPUT_TYPE.TEXTBOX,
        label: 'Enter full name',
        maxLength: 50,
        isError: false,
        type: 'text',
        errormsg: 'Enter a valid Name',
        placeholder : 'Enter full name',
        value: '',
        visible : true,
        error : false,
       

    },
    targetRole: {
        id: 'targetrole',
        inputType: textConstants.INPUT_TYPE.TEXTBOX,
        label: 'Role you are looking for',
        maxLength: 50,
        isError: false,
        type: 'text',
        value: '',
        errormsg: 'Enter a valid target role',
        placeholder : 'ex: Frontend Developer',
        visible : true,
    },
    targetCompany: {
        id: 'targetcompany',
        inputType: textConstants.INPUT_TYPE.TEXTBOX,
        label: 'Target company name',
        maxLength: 50,
        isError: false,
        value: '',
        type: 'text',
        errormsg: 'Enter a valid Name',
        placeholder : 'ex: Google',
        visible : true,


    },
    workExperience: {
        id: 'workexperience',
        inputType: textConstants.INPUT_TYPE.TEXTBOX,
        label: 'Work experience in years',
        maxLength: 10,
        isError: false,
        type: 'text',
        value: '',
        errormsg: 'Enter a valid years',
        placeholder : 'ex: 4',
        visible : true,
    },
    mobileNumber: {
        id: 'mobilenumber',
        inputType: textConstants.INPUT_TYPE.TEXTBOX,
        label: 'Enter valid mobilenumber',
        maxLength: 10,
        value: '',
        isError: false,
        type: 'number',
        errormsg: 'Enter valid mobile number',
        placeholder  : '9148292452',
        visible : true,

    },
    skills: {
        id: 'skills',
        inputType: textConstants.INPUT_TYPE.TEXTBOX,
        label: 'Add skills',
        maxLength: 100,
        isError: false,
        value: '',
        type: 'text',
        errormsg: 'Enter a skills',
        placeholder  : 'Search and add skills',
        visible : true,
    }
  }

  const alphabetObject = {
    a: ["accountant", "architect", "actor", "artist", "astronomer", "athlete", "attorney", "administrator", "analyst", "aircraft pilot"],
    b: ["baker", "bartender", "biologist", "butcher", "builder", "banker", "broker", "brewer", "blacksmith", "botanist"],
    c: ["chef", "chemist", "coach", "carpenter", "composer", "consultant", "clerk", "counselor", "cartographer", "computer programmer"],
    d: ["dentist", "doctor", "designer", "detective", "dancer", "driver", "dietitian", "draftsman", "developer", "diplomat"],
    e: ["engineer", "electrician", "editor", "economist", "embalmer", "entrepreneur", "epidemiologist", "educator", "environmentalist", "entertainer"],
    f: ["farmer", "firefighter", "fisherman", "florist", "film director", "financial planner", "fashion designer", "forester", "freelancer", "flight attendant"],
    g: ["geologist", "graphic designer", "gardener", "glassblower", "genealogist", "gynecologist", "game developer", "golfer", "genealogist", "gamer"],
    h: ["hairdresser", "historian", "housekeeper", "hacker", "hotel manager", "horticulturist", "hematologist", "handyman", "home inspector", "harpist"],
    i: ["illustrator", "interpreter", "insurance agent", "investment banker", "ironworker", "industrial engineer", "immunologist", "instructor", "interior designer", "IT specialist"],
    j: ["judge", "journalist", "jeweler", "janitor", "jockey", "juggler", "joiner", "jailer", "jester", "jewelry designer"],
    k: ["kinesiologist", "kitchen designer", "kidney specialist", "knight", "knitter", "kindergarten teacher", "karate instructor", "kayak instructor", "keyboardist", "kite instructor"],
    l: ["lawyer", "librarian", "locksmith", "landscaper", "laborer", "linguist", "life coach", "leatherworker", "loan officer", "lifeguard"],
    m: ["mechanic", "musician", "mathematician", "model", "magician", "marine biologist", "mason", "miner", "meteorologist", "massage therapist"],
    n: ["nurse", "nutritionist", "news anchor", "novelist", "notary", "neurologist", "nanny", "navigator", "nutritionist", "numismatist"],
    o: ["optometrist", "occupational therapist", "oceanographer", "office manager", "organist", "obstetrician", "ophthalmologist", "orthodontist", "ornithologist", "operator"],
    p: ["photographer", "painter", "physician", "pilot", "plumber", "pharmacist", "paramedic", "paleontologist", "podiatrist", "psychologist"],
    q: ["quartermaster", "quilter", "quantitative analyst", "quality control inspector", "quarantine officer", "quick sketch artist", "quarry worker", "quantum physicist", "quantum mechanic", "quartermaster"],
    r: ["radiologist", "realtor", "reporter", "ranger", "referee", "radiographer", "receptionist", "refrigeration technician", "reflexologist", "researcher"],
    s: ["scientist", "singer", "surgeon", "soldier", "sailor", "secretary", "statistician", "security guard", "software developer", "scuba instructor"],
    t: ["teacher", "technician", "tailor", "therapist", "truck driver", "taxidermist", "telecommunications specialist", "tour guide", "town planner", "taxonomist"],
    u: ["urologist", "umpire", "underwriter", "urban planner", "undertaker", "usher", "ultrasound technician", "upholsterer", "union representative", "utility worker"],
    v: ["veterinarian", "violinist", "vintner", "videographer", "ventriloquist", "vocal coach", "volcanologist", "voice actor", "volleyball coach", "veterinary technician"],
    w: ["writer", "web developer", "welder", "waiter", "window cleaner", "woodworker", "wheelwright", "wildlife biologist", "wine taster", "waste collector"],
    x: ["X-ray technician", "Xenobiologist", "Xylophonist", "Xenophotographer", "Xenolinguist", "Xylographer", "Xenobiologist", "Xylographer", "Xenologist", "Xenobiotechnologist"],
    y: ["yoga instructor", "youth counselor", "yacht captain", "yacht broker", "yodeler", "yardmaster", "yeoman", "yacht designer", "yield broker", "yogurt maker"],
    z: ["zoologist", "zookeeper", "zither player", "zookeeper", "zamboni driver", "zeppelin pilot", "zip line instructor", "zinc miner", "zookeeper", "zookeeper"]
};

const professionalSkills = [
    "Programming Languages (e.g., Python, Java, JavaScript)",
    "Problem-Solving",
    "Critical Thinking",
    "Communication Skills (Verbal and Written)",
    "Teamwork",
    "Data Analysis",
    "Technical Writing",
    "Project Management",
    "Time Management",
    "Research Skills",
    "Mathematics",
    "Creativity",
    "Leadership",
    "Adaptability",
    "Software Development",
    "Analytical Skills",
    "Attention to Detail",
    "Computer-Aided Design (CAD)",
    "Statistical Analysis",
    "Public Speaking",
    "Collaboration",
    "Version Control (e.g., Git)",
    "Data Visualization",
    "Database Management",
    "Systems Thinking",
    "Networking",
    "Cybersecurity",
    "Machine Learning",
    "Artificial Intelligence",
    "Mobile Development",
    "User Experience (UX) Design",
    "Agile Methodologies",
    "Cloud Computing",
    "Quality Assurance",
    "Internet of Things (IoT)",
    "Robotics",
    "3D Printing",
    "Virtual Reality (VR) Development",
    "Augmented Reality (AR) Development",
    "Automation",
    "Embedded Systems",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Industrial Engineering",
    "Environmental Engineering",
    "Structural Engineering",
    "Aerospace Engineering",
    "Materials Science",
    "Energy Systems",
    "Control Systems",
    "Renewable Energy",
    "Nanotechnology",
    "Biomedical Engineering",
    "Bioinformatics",
    "Computational Fluid Dynamics (CFD)",
    "Finite Element Analysis (FEA)",
    "Systems Engineering",
    "Risk Management",
    "Decision Making",
    "Conflict Resolution",
    "Machine Vision",
    "Natural Language Processing (NLP)",
    "Big Data Analytics",
    "DevOps",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Information Security",
    "Robotics Process Automation (RPA)",
    "Blockchain Development",
    "Quantum Computing",
    "Digital Twin",
    "Mixed Reality",
    "Cyber-Physical Systems",
    "Rapid Prototyping",
    "Product Lifecycle Management (PLM)",
    "Data Mining",
    "Predictive Modeling",
    "Geospatial Analysis",
    "Systems Simulation",
    "Industrial Automation",
    "Sensor Fusion",
    "Cognitive Computing",
    "Edge Computing",
    "Model-Based Design",
    "Systems Integration",
    "Fault Diagnosis",
    "Reliability Engineering",
    "Machine-to-Machine (M2M) Communication",
    "Cloud Security",
    "Reverse Engineering",
    "Human-Computer Interaction (HCI)",
    "Data Warehousing",
    "Distributed Systems",
    "Elastic Computing",
    "Containerization",
    "Cyber Threat Intelligence",
    "Digital Signal Processing",
    "Embedded Firmware Development",
    "Voice User Interface (VUI) Design",
    "frontend",
    "frontend coding",
    "frontend engineering",
    "frontpage",
    "frontend design",
    "frontend development",
    "front desk",
    "front office",
    "sistema frontend",
    "front office development",
    "front office support",
    "front office trading systems",
    "front to back office",
    "frontline management",
    "software prototyping",
    "software",
    "software analysis",
    "software projects",
    "softwareentwicklung",
    "softwareprojektleitung",
    "softwaretechnik",
]


  export  {
    skills,
    formDataConfig,
    alphabetObject,
    professionalSkills,
  }